apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: moto
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - port: 9187
      targetPort: 9187
      protocol: TCP
  type: ClusterIP
